server:
  port: 9097

 
eureka:
  instance:
    appname: at-documentation-swagger-api
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
      
swagger: 
  config: 
    refreshrate: 5000

spring:
  application:
    name: at-documentation-swagger-api

management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'